[MIG] #2494 firefox sfit
sunflowerit/sfit-timer pull request #3
Opened 2022-01-26 22:59 UTC by KKamaa

So currently a WIP still requires some testing though works fine see test sample below

https://user-images.githubusercontent.com/10249832/151260885-bb6057d3-20da-46bc-99c1-1f216c3557c5.mp4

Seemed like there wasn't much to re-develop in firefox apart from a few changes though had to go through the firefox docs just to understand a few things. I will be pushing changes as I use it in recording time.

[QA] - how do we handle mins and seconds? Do we just record the hours, think this might be the first place to check fields float _unit_amount_.

2022-02-02 09:56 UTC, thomaspaulb requested changes

2022-02-02 09:56 UTC, thomaspaulb commented on src/js/_localstorage.js
> +if (typeof chrome !== 'undefined' && browser.storage && browser.storage.local) {
When using this branch in Chrome, getting:

![image](https://user-images.githubusercontent.com/1466356/152130617-c989d335-cdbc-4bc5-a1e3-0c49929747ee.png)

Seems it can be solved by including this polyfill:

https://github.com/mozilla/webextension-polyfill/

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension#the_webextension_browser_api_polyfill

2022-02-02 09:56 UTC, thomaspaulb commented on src/js/_main.js
> +        console.log("called sasa!");
:-)

2022-02-03 08:58 UTC, KKamaa commented on src/js/_localstorage.js
> +if (typeof chrome !== 'undefined' && browser.storage && browser.storage.local) {
@thomaspaulb think if we go the cross browse way it might be expensive to maintain with new updates to both firefox and chrome since we have to modify the callback to use promises and also I see the lib affects the current angular lib we have so it might lead a redo to accommodate all the change well and since we are using it on a daily basis might be kind frustrating to the team. So what I did was followed the firefox tutorial on this and currently testing it on firefox, we could a maybe have separate branches for now chrome and firefox as we do the cross platform in a different branch and explore new options and compatibilities with other browsers. Just my thoughts on it?

2022-02-03 13:50 UTC, thomaspaulb commented
@KKamaa About the minutes and seconds, it is not important, I think we are using it only for visualization so that we can see a nice running timer, but when we save the timesheet line, we are rounding to multiples of 15 minutes.

2022-02-03 13:53 UTC, thomaspaulb commented on src/js/_localstorage.js
> +var is_firefox = /firefox/i.test(navigator.userAgent);
@KKamaa I'm sure this works, but why did you make it very complicated?

Couldnt you just have included

https://github.com/mozilla/webextension-polyfill

and then include

`<script type="module" src="browser-polyfill.js"></script>`

on the top of the page?

Then after that, you will have a working `browser` object, in Chrome as well as Firefox.

2022-02-03 16:37 UTC, KKamaa commented on src/js/_localstorage.js
> +var is_firefox = /firefox/i.test(navigator.userAgent);
@thomaspaulb this was my old commit before I texted you in the chat.

2022-02-07 07:31 UTC, thomaspaulb commented
@KKamaa  - this is the older branch right? Maybe close and remove

2022-02-07 10:08 UTC, closed without merging